### ISSUE TITLE
Wacca is now playable

### ISSUE THREAD

**Issue by Lava3063** [xiaopeng12138/WACVR#1]
Wacca S is now playable, check 1cc discord for more information

https://discord.gg/dsB9pHAcPz

Cant link as much stuff as id like, otherwise id probably get banned/flagged

**Comment by xiaopeng12138** [comment]
4103 error

**Comment by xiaopeng12138** [comment]
got it

**Comment by C-F0x** [comment]
> Wacca S is now playable, check 1cc discord for more information
> 
> https://discord.gg/dsB9pHAcPz
> 
> Cant link as much stuff as id like, otherwise id probably get banned/flagged

hello,could u update the discord invite plz

**Comment by Nbisbo** [comment]
discord is dead
