### ISSUE TITLE
WACVR screen flick on Windows 10 21h2

### ISSUE THREAD

**Issue by leo0215** [xiaopeng12138/WACVR#12]
random flick occured during playing on Gaming Laptop

GPU,Intel Graphic X-re,RTX3060 Laptop GPU
OS:Windows 10 21h2 build:19044.1706

uWindowsCapture:1.1.2

**Comment by xiaopeng12138** [comment]
ok i think it's a issue because your have reverse and the game window title is maybe not same as llr version

**Comment by xiaopeng12138** [comment]
and is it ok that you post n+0 video?

**Comment by leo0215** [comment]
like this

https://user-images.githubusercontent.com/37405572/169300133-faf89a21-b666-4c5c-ae46-23509ed0b1f0.mp4

**Comment by xiaopeng12138** [comment]
> like this
> 
> https://user-images.githubusercontent.com/37405572/169300133-faf89a21-b666-4c5c-ae46-23509ed0b1f0.mp4
> 
> 

oh, that is way worst than what I expected. I will check it today

**Comment by ItsCharaHere** [comment]
I think that it could possibly be an unavoidable issue with tabbing out of xxxxx.exe, from my personal testing this never happens until I tab into another app like WACVR or discord, it's best to just keep xxxxx.exe focused to mitigate it

**Comment by leo0215** [comment]
weird I am sure I didn't tab out game exe,and keep it focus

**Comment by ItsCharaHere** [comment]
I'll look into it more tonight

**Comment by ItsCharaHere** [comment]
i have a plan to possibly fix this, will update next week

**Comment by leo0215** [comment]
after reinstalled Windows 10 21h1,screen random flick no longer occured,I assume it is my laptop's some file corruption
