### ISSUE TITLE
White Enviroment & Model

### ISSUE THREAD

**Issue by Lava3063** [xiaopeng12138/WACVR#31]
Everything is 
white, except for the game capture

![Screenshot (9)](https://user-images.githubusercontent.com/52802454/172501217-3b834e69-dc92-43b0-9434-ef5b7f6938d7.png)

**Comment by Lava3063** [comment]
Using artifact of latest commit, previous commit, (skybox & model change) has the same issue

**Comment by xiaopeng12138** [comment]
> Using artifact of latest commit, previous commit, (skybox & model change) has the same issue

I think this is Github action issue which is not in my charge. @burritosoftware

**Comment by burritosoftware** [comment]
Will check up on it but likely not Actions' issue because it builds directly on the right editor on Windows so the build may be missing something (it would fail though if there's an error so maybe a mistake, have to check xpeng's new commit)

**Comment by Lava3063** [comment]
Newest build works, issue is not there. Closing issue

**Comment by xiaopeng12138** [comment]
the issue is because lighting bake is set to use gpu and apparently github action don't have gpu
