### ISSUE TITLE
Crash on headset enable

### ISSUE THREAD

**Issue by blstrManx** [xiaopeng12138/WACVR#35]
Tried running on an Oculus CV1 and a Quest 2, with both, the program crashes when I put on the headset, or when the light that detects your head is covered. If launched with the light covered/headset on, the program crashes instantly. When running the game simulated without putting on the headset, the image appears in the proper place, and output seems like it's working properly.

Attached is my uWindowCapture.log and my Player.log(s).
[uWindowCapture.log](https://github.com/xiaopeng12138/WACVR/files/9215147/uWindowCapture.log)
[Player.log](https://github.com/xiaopeng12138/WACVR/files/9215149/Player.log)
[Player-prev.log](https://github.com/xiaopeng12138/WACVR/files/9215150/Player-prev.log)

**Comment by xiaopeng12138** [comment]
Have you tried other version of action artifacts? the dev branch is very unstable and may cause some issue

**Comment by blstrManx** [comment]
Yep, that got it! Was just confused as a friend got the latest version working on their end and was directing me through setup, but I went back to version #22 and it works fine!

**Comment by xiaopeng12138** [comment]
the latest build should also work, my quest2 dont have any issue

**Comment by xiaopeng12138** [comment]
look like the last build still has this issue. may cause by leap motion things or update of openxr package

**Comment by xiaopeng12138** [comment]
> Tried running on an Oculus CV1 and a Quest 2, with both, the program crashes when I put on the headset, or when the light that detects your head is covered. If launched with the light covered/headset on, the program crashes instantly. When running the game simulated without putting on the headset, the image appears in the proper place, and output seems like it's working properly.
> 
> Attached is my uWindowCapture.log and my Player.log(s).
> [uWindowCapture.log](https://github.com/xiaopeng12138/WACVR/files/9215147/uWindowCapture.log)
> [Player.log](https://github.com/xiaopeng12138/WACVR/files/9215149/Player.log)
> [Player-prev.log](https://github.com/xiaopeng12138/WACVR/files/9215150/Player-prev.log)
> 
> 

are you using win 11?

**Comment by blstrManx** [comment]
I am on win 10.

**Comment by xiaopeng12138** [comment]
> I am on win 10. Also worth noting, I'm not using leap motion, just oculus touch controllers.

it's very strange, I have quest 2 and also don't have leap motion and the latest build work for me

**Comment by xiaopeng12138** [comment]
> I am on win 10. Also worth noting, I'm not using leap motion, just oculus touch controllers.

can you please also send the crash repor file? the file path is in the last line of your player.log

**Comment by blstrManx** [comment]
Looks like I can't upload the dmp directly, so here's a zip.
[Crash_2022-07-28_222259237.zip](https://github.com/xiaopeng12138/WACVR/files/9229691/Crash_2022-07-28_222259237.zip)

**Comment by xiaopeng12138** [comment]
> Looks like I can't upload the dmp directly, so here's a zip. [Crash_2022-07-28_222259237.zip](https://github.com/xiaopeng12138/WACVR/files/9229691/Crash_2022-07-28_222259237.zip)

does latest commit fix the issue?

**Comment by blstrManx** [comment]
I tried the build #37, still crashes. Here's some more dmp zips.
CV1 crash:
[Crash_2022-08-01_180048126.zip](https://github.com/xiaopeng12138/WACVR/files/9236156/Crash_2022-08-01_180048126.zip)
Quest 2 crash:
[Crash_2022-08-01_180420980.zip](https://github.com/xiaopeng12138/WACVR/files/9236157/Crash_2022-08-01_180420980.zip)

**Comment by xiaopeng12138** [comment]
the latest dev build should work now. the issue was leapmotion and openxr stuff

**Comment by blstrManx** [comment]
It works!
