### ISSUE TITLE
LED not working

### ISSUE THREAD

**Issue by RubberDuckShobe** [xiaopeng12138/WACVR#38]
I'm using segatools from the wacvr-dev branch and the latest WACVR build from GitHub Actions, IPC is enabled and touch input works but the LEDs don't work.
The game instantly reports that the LED test failed

**Comment by xiaopeng12138** [comment]
If your led test failed, it's may because of you don't have ftd2xx.dll. You need to find right version of ftd2xx.dll then put it next to the games shipping exe

**Comment by RubberDuckShobe** [comment]
Thank you! It works now.
