### ISSUE TITLE
Design updates similar to MaiDXR

### ISSUE THREAD

**Issue by burritosoftware** [xiaopeng12138/WACVR#39]
Bring design improvements from MaiDXR to WACVR after stable release

**Comment by xiaopeng12138** [comment]
that's exactly my plan. but for logo i need to ask my friend first

**Comment by xiaopeng12138** [comment]
https://github.com/xiaopeng12138/WACVR/commit/70759368ef39d9eaabadd3066d780b8632d440a2
#46
