### ISSUE TITLE
how does work it? 

### ISSUE THREAD

**Issue by Cronicle00** [xiaopeng12138/WACVR#43]
i wanted try playing this map but i don't know how to play this map.
can you teach me? 
i'm already set git setting

**Comment by xiaopeng12138** [comment]
you need first to have original game running. then just follow the com0com setup of my another repo MaiDXR

**Comment by xiaopeng12138** [comment]
pls see the latest readme for more details

**Comment by Cronicle00** [comment]
Okay thx to consider me

2022년 10월 9일 (일) 오전 2:22, xpeng ***@***.***>님이 작성:
