### ISSUE TITLE
LIV not showing model

### ISSUE THREAD

**Issue by KenahlOwO** [xiaopeng12138/WACVR#44]
My model that I have on LIV is not showing when I select WACVR as the source, it seems that WACVR just overlays on top of the model, when I turn off the “use SDK” I see my VR view and an outline of the model only… is there possibly anything that needs to be edited with the LIV code in WACVR in order to have the model show correctly?

**Comment by xiaopeng12138** [comment]
I will check it later, because the new version is still work in progress. I need to finish the setting panel rewrite first.

**Comment by KenahlOwO** [comment]
hmm, I'm using the old version, (the one that has the panel on the side, not on the machine) when I use the new version, the one with the options on the machine and on the top, that doesn't show up at all on LIV.

**Comment by xiaopeng12138** [comment]
> hmm, I'm using the old version, (the one that has the panel on the side, not on the machine) when I use the new version, the one with the options on the machine and on the top, that doesn't show up at all on LIV.

can you pls try the latest build?

**Comment by xiaopeng12138** [comment]
need further information to open this issue
