### ISSUE TITLE
Add LED

### ISSUE THREAD

**Issue by xiaopeng12138** [xiaopeng12138/WACVR#6]
I don't think it is possible because of the custom usb protocol.

**Comment by Frityet** [comment]
> So we now have basic led thanks ItsCharaHere. But if we want the original led we need to hook into game or make our own USB dll.

Could you elabourate further? I have been reading up on the USB spec for osdev, and I am intrested on trying to help

**Comment by xiaopeng12138** [comment]
> > So we now have basic led thanks ItsCharaHere. But if we want the original led we need to hook into game or make our own USB dll.
> 
> Could you elabourate further? I have been reading up on the USB spec for osdev, and I am intrested on trying to help

you can find a usb dll in games plugin folder. the function in it contains everything we need. we just need to get the argument that is passed in to function and then hook it.

**Comment by xiaopeng12138** [comment]
[9919fabcf61dd2ed6f0f1cb7df75343ad4c3fa9d](https://github.com/xiaopeng12138/WACVR/commit/9919fabcf61dd2ed6f0f1cb7df75343ad4c3fa9d)
