### ISSUE TITLE
Mercury.zip fails to download

### ISSUE THREAD

**Issue by Danorexic** [xiaopeng12138/WACVR#69]
The Mercury.zip file is not accessible through the Powershell script. When attempting to download through a web browser, it gives:
Forbidden
You don't have permission to access this resource.Server unable to read htaccess file, denying access to be safe

**Comment by xiaopeng12138** [comment]
Server issue. It should be fixed now

**Comment by Danorexic** [comment]
Thanks for the quick fix!
