### ISSUE TITLE
White Screen

### ISSUE THREAD

**Issue by leo0215** [xiaopeng12138/WACVR#8]
seem WACVR failed to capture WACCA and it keep pop up Serial port is not open Error,and I running wacca and WACVR on laptop
[Player.log](https://github.com/xiaopeng12138/WACVR/files/8712920/Player.log)
r
![OculusScreenshot1652841655](https://user-images.githubusercontent.com/37405572/168946985-31ceb1d1-2f94-44e1-be7c-750373297e6e.jpeg)

**Comment by ItsCharaHere** [comment]
You did not install uWindowCapture, see: https://github.com/xiaopeng12138/MaiDXR

**Comment by leo0215** [comment]
thanks,I just installed uWindowCapture,and it have screen now,but I am stuck with emulator touch device is not working even I reconnect device via test menu,should comport in serial.cs same as wacca's ?

**Comment by leo0215** [comment]
![OculusScreenshot1652880425](https://user-images.githubusercontent.com/37405572/169050383-a49252a4-e6f1-42c8-ab9d-00c81dcba601.jpeg)

**Comment by ItsCharaHere** [comment]
Try reopening WACVR then wacca after, the serials should be the same

**Comment by ItsCharaHere** [comment]
> Try reopening WACVR then wacca after, the serials should be the same

Also be sure to set your apps that open with wacca. & WACVR itself to open as admin
XXXX.exe > properties > compatability > open as admin

**Comment by leo0215** [comment]
thanks,it all worked.appreciated
